services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8081:80



  db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointments

    ports:
      - 3306

    volumes:
      - ./db:/docker-entrypoint-initdb.d

